### ISSUE TITLE
howto replace localhost:8080 and localhost:3000 with FQDN

### ISSUE THREAD

**Issue by ismailyenigul** [DivanteLtd/vue-storefront#1292] opened 2018-06-13 21:26 UTC
Hi,

What is the proper way to access vue-storefront and vue-storefront-api over and fqdn instead of localhost? which files should I edit to make it work.
right now I only edit config/local.json file on both project. But I see that vue-storefront still try to access localhost:8080 for API.

**Comment by pkarw** [comment] 2018-06-15 17:41
Duplicate of #1290

**Closed by pkarw** 2018-06-15 17:41 UTC
