### ISSUE TITLE
This page isn't working - localhost didn't send any data.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3259] opened 2019-07-19 12:57 UTC
## Current behavior
Problem with running vsf on the newest develop.

I get message: **_This page isn't working - localhost didn't send any data._**

`app_1  | [search] Can not connect the vue-storefront-api / ElasticSearch instance! Error: {"root_cause":[{"type":"parsing_exception","reason":"No value specified for terms query","line":1,"col":170}],"type":"parsing_exception","reason":"No value specified for terms query","line":1,"col":170}
app_1  |     at SearchAdapter.exports.modules../core/lib/search/adapter/api/searchAdapter.ts.SearchAdapter.handleResult (vsf-search-adapter-0.server-bundle.js:544:23)
app_1  |     at Object.resultPorcessor (vsf-search-adapter-0.server-bundle.js:570:30)
app_1  |     at server-bundle.js:2174:80
app_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
app_1  | Problem with setting Category initial data! Error: {"root_cause":[{"type":"parsing_exception","reason":"No value specified for terms query","line":1,"col":170}],"type":"parsing_exception","reason":"No value specified for terms query","line":1,"col":170}
app_1  |     at SearchAdapter.exports.modules../core/lib/search/adapter/api/searchAdapter.ts.SearchAdapter.handleResult (vsf-search-adapter-0.server-bundle.js:544:23)
app_1  |     at Object.resultPorcessor (vsf-search-adapter-0.server-bundle.js:570:30)
app_1  |     at server-bundle.js:2174:80
app_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
app_1  | Top-most asyncData executed null
app_1  | Result from ES for 960c6492441347941025f2b095113aa2be6400182993df1bf7fe9646 (category),  ms=64 null
app_1  | whole request [/c/men-11]: 503ms`

## Expected behavior
vsf should work correctly

## Steps to reproduce the issue
1. switch to develop
2. git pull
3. yarn
4. yarn dev

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by patzick** [comment] 2019-07-22 09:07
Closing - caused by config mismatch.

**Closed by patzick** 2019-07-22 09:07 UTC
Labels: bug

**Comment by supimon** [comment] 2020-04-30 16:59
came across a similar issue but this time the error is as follows:

```
[search] Can not connect the vue-storefront-api / ElasticSearch instance! Error: {"code":500,"result":{"diagnosticText":"src/processor/default.ts(25,48): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'string | Query | (string | Query)[] | ((searchString: string, position?: number) => number) | ((searchElement: string | Query, fromIndex?: number) => number)' has no compatible call signatures.\n","diagnosticCodes":[2349]}}
    at SearchAdapter.exports.modules../core/lib/search/adapter/api/searchAdapter.ts.SearchAdapter.handleResult (vsf-search-adapter-0.server-bundle.js:519:23)
```

The page therefore reports internal server error.
