### ISSUE TITLE
Email address is needed to give a feedback

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2814] opened 2019-04-26 11:12 UTC
## What is the motivation for adding / enhancing this feature?
When user is not logged in then he can't give a feedback, because his email is not charged from the checkout.
![image](https://user-images.githubusercontent.com/36628922/56803996-92a66300-6824-11e9-8aeb-efc8b23cc23a.png)

## What are the acceptance criteria 
We need create special field for email address or address must be taken from the checkout.

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by ZeevGerstner** [comment] 2019-04-28 17:00
I will add this

**Comment by pkarw** [comment] 2019-05-01 16:14
we need to just get the e-mail address from the checkout form and add it to the message body

**Comment by ZeevGerstner** [comment] 2019-05-02 10:45
So just add use email to the feedback? Where? Before the content? How it'll resolve the error of checkoutPersonalEmailAddress when the user is a guest?
Think Im missing something...

**Comment by pkarw** [comment] 2019-05-02 11:13
@ZeevGerstner  it’s up to you; no strong preferences. We do have the email as this page is visible only after order has been placed

**Comment by ZeevGerstner** [comment] 2019-05-02 16:13
You are right but still we getting that error that Source email address is not provided.
That's what should happen?
Any way all you want is that i'll add in the emailText the user mail? if so do you want to show it to the user or just add it to his feedback?

**Comment by webdiver** [comment] 2019-05-24 09:03
[vuestore-hackathon] I will tackle this one now.

**Comment by webdiver** [comment] 2019-05-24 09:41
It seems, the problem is the server itself.

The request is correctly send to the server:
```
emailText: "qsdasd"
sourceAddress: "asdasd@everycademy.de"
subject: "What we can improve?"
targetAddress: "contributors@vuestorefront.io"
token: "eyJ0..."
```

But the response is:
```
code: 500
result: "Invalid email address is provided!"
```

**Comment by alinadivante** [comment] 2019-07-22 10:17
Hey, there is still no way to send feedback.
please see my screenshot
![image](https://user-images.githubusercontent.com/36628922/61625298-aa9e4f00-ac7a-11e9-9d4d-3bb2af5d864a.png)

**Comment by Michal-Dziedzinski** [comment] 2019-07-22 10:44
@alinadivante it's another error, the one above has been fixed in #3265. Widocznie ten z #2814 został naprawiony przez kogoś innego.

**Comment by Michal-Dziedzinski** [comment] 2019-07-22 10:45
@alinadivante it's another error, the one above has been fixed in #3265. Apparently the one from # 2814 has been repaired by someone else.

**Comment by alinadivante** [comment] 2019-07-22 11:17
ok, so I'm waiting for my `Ready for QA` label 😄

**Comment by alinadivante** [comment] 2019-08-20 06:25
checked on https://test.storefrontcloud.io/ environment - Email has successfully been sent 👌

**Comment by Michal-Dziedzinski** [comment] 2020-01-21 08:22
@alinadivante @pkarw shouldn't it be closed?

**Comment by pkarw** [comment] 2020-01-21 09:48
Thx

**Closed by pkarw** 2020-01-21 09:48 UTC
Labels: 1: Easy, feature request, vs-hackathon
