### ISSUE TITLE
config.i18n.bundleAllStoreviewLanguages breaks build process, config value seems to be inconsistent.

### ISSUE THREAD

**Issue by cartok** [DivanteLtd/vue-storefront#3188] opened 2019-07-05 13:01 UTC
## Current behavior
Setting config.i18n.bundleAllStoreviewLanguages to false breaks the build process.

The webpack base config loads the 'config' npm package, that returns a merged config object (default, local), then this config is written to to the webpack config directory as 'config.json'. The config gets passed to translationPreprocessor.default. That function checks 'config.i18n.bundleAllStoreviewLanguages' and if it's true, it writes a file named 'multistoreLanguages.json' to 'core/resource/i18n'. The webpack alias that is set for 'config' will now return the previously written config file, meaning that the 'config' npm package is only used once for merging the files (it's imported using the same name). Webpack will then execute the entry-point scripts.
Those import i18n from 'core/i18n/index.ts'. Inside of that file VueI18n gets instantiated, checking 'config.i18n.bundleAllStoreviewLanguages' and if it's true it will require 'core/i18/resource/i18n/multistoreLanguages.json'.
Having set 'bundleAllStoreviewLanguages' to false should prevent requiring that not existing file. Remember: it was not created in 'translationPreprocessor'. Somehow it still tries to require that file. 

## Steps to reproduce the issue
* Set 'config.i18n.bundleAllStoreviewLanguages' to false
* Delete 'core/i18n/resources/i18n/multistoreLanguages.json' if it exists from previous build
* yarn dev | yarn build

## Repository
Everywhere

## Can you handle fixing this bug by yourself?
- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
current & previous

## Environment details
- OS: Windows 10 -> Vagrant 2.2.4 -> Arch Linux 4.20.13
- Node: v10.15.3
- Code Version: master,develop,custom

## Additional information
I tried it without 'config' npm package, using a different minimalistic one to merge the configs manually. Did not help.

**Comment by pkarw** [comment] 2019-07-06 14:52
Thanks for raising this issue. We will try to reproduce and fix it

**Comment by pkarw** [comment] 2019-07-06 20:39
This is caused by webpack trying to bundle this file into the app bundle anyway - webpack doesn't support the runtime conditions (as checking the config variable in that case) and always bundles the required files (like doing this bundling kind of statically - which makes perfect sense as while compiling the current config can't be obtained from the webpack perspective)

**Comment by pkarw** [comment] 2019-07-06 20:42
Fixed by the #3189

**Closed by pkarw** 2019-07-06 20:42 UTC
Labels: 3: Medium complexity, P2: Important, bug
