### ISSUE TITLE
Back button not properly working from a configurable product page

### ISSUE THREAD

**Issue by thierry2015** [DivanteLtd/vue-storefront#1699] opened 2018-09-05 15:01 UTC
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
When I click on the back button in a variant product detail page (configurable-product route), I am redirected to the product detail page (configurable-product), that redirects me to the configurable-product route again, causing a dead-end navigation.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  - From a product list page, click on a configurable product
  - The URL should be /p/12.34.56/my-product-slug/12.34.56.78 (configurable-product)
  - Click on the back button in the header
  - The URL will be, for a short time, /p/12.34.56.78/my-product-slug
  - A redirection will occur, to /p/12.34.56/my-product-slug/12.34.56.78

* **What is the expected behavior?**
The back button should redirect to the last route, ignoring any redirection and go to the last real navigable route

* **What is the motivation / use case for changing the behavior?**
The user experience is really affected by this issue. Any website using configurable products will be heavily affected on the navigation side.

* **Please tell us about your environment:**
  
  - Version: @vue-storefront/theme-default@1.2.0
  - Browser: [all]
  - Language: [ES6/7]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
https://vuestorefront.slack.com/archives/CA68P1JUF/p1536158237000100

**Comment by pkarw** [comment] 2018-09-05 15:07
Thanks! You mean the arrow button in the VS UI and not the browser back button correct?

**Comment by thierry2015** [comment] 2018-09-05 15:08
Correct, the VS header back button

**Comment by pkarw** [comment] 2018-09-27 06:17
@thierry2015 can You please check if the issue is still valid on current develop branch?

**Comment by pkarw** [comment] 2018-09-29 14:36
@qiqqq the problem is that if you enter the url of single product VS is redirecting you to the main configurable - therefore when clicking history.back(-1) you’re looping to single - configurable page on and on

**Comment by pkarw** [comment] 2018-09-29 14:37
Maybe ij this case we should a) use not redirect but other way to transfer user to the right page, b) have an option for back button to force the back url in this particular case m?

**Comment by pkarw** [comment] 2018-12-03 07:35
@qiqqq could You please take care of this issue?

**Comment by qiqqq** [comment] 2019-01-15 11:21
@thierry2015 Fix for this bug is now merged to master. Can you confirm this bug not occurs now?

**Comment by thierry2015** [comment] 2019-01-15 14:59
I will update the version during my next sprint and test it. If no update in 3 weeks, consider it done

**Closed** 2019-03-02 11:29 UTC
Labels: bug, vs-hackathon
