### ISSUE TITLE
Erin Recommends filter doesn't work with other filters (color and size)

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2714] opened 2019-04-12 10:45 UTC
## Current behavior

When I want to filter products only by Erin recommends (without other filters), the filter results are displayed correctly (according to the setting of the Edin recommendations parameter in the magento product edition).
The same for choosing filters at once: price and Erin recommends.

**However, when I use additional filters: color or size, then selecting the Erin recommends filter, there is no results - for both 'No' and 'Yes'.**

![ErinRecommendsfilter](https://user-images.githubusercontent.com/49188852/56030198-8d252500-5d1c-11e9-9ee0-e0ea79420aff.gif)

## Expected behavior

When I use filters at once: color or size (or both) and then the Erin recommends filter - there is a product list visible as the result - according to the slected filters and the setting of the Edin recommendations parameter in the magento product edition.

## Steps to reproduce the issue

1. Go to https://test.storefrontcloud.io/
2. Click on 'Offline Casual' section on home page
3. Choose any filter color/size (one is enough)
4. Choose Erin recommends 'No'
5. Choose Erin recommends 'Yes'

## Can you handle fixing this bug by yourself?

- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Windows 10

## Additional information
Each product has as a default 'Erin recommend' parameter  set as 'No'  (in magento product edition). If no product appears after selecting 'Yes', all products should be visible for 'No' option.

**Comment by pkarw** [comment] 2019-04-12 18:23
The problem is that the filters ARE NOT refreshing themselves when another filter is being selected. It might be good idea to improve it!

**Comment by pkarw** [comment] 2019-04-12 18:47
Related to (Duplicate of): #2322

**Closed** 2019-07-05 12:21 UTC
Labels: feature request, vs-hackathon

**Comment by alinadivante** [comment] 2019-07-05 12:26
Closed as duplicate of: #2322
