### ISSUE TITLE
Wrong version of cart when selecting shipping method in checkout

### ISSUE THREAD

**Issue by heaenwie** [DivanteLtd/vue-storefront#5266] opened 2020-11-30 16:29 UTC
## Current behavior

The versioning of the cart is broken and after you purchase something, the wrong cart number is stored and you cannot proceed with the checkout. 

## Steps to reproduce the issue

Steps to reproduce:
1. Login on account mciesielska@divante.pl - order products - success;
2. Log out
3. login on another account (mciesielska+1@divante.pl) - order products - proceed to shipping. Error shows when clicking select shipping method, error:

Checkout error: [VSF][error] [GraphQL error]: Message: Object fbb927f3-e23b-4895-9012-64b015763785 has a different version than expected. Expected: 118 - Actual: 124., Location: [column: 3, line: 303], Path: cart
64285f5.modern.js:2 Uncaught (in promise) Error: GraphQL error: Object fbb927f3-e23b-4895-9012-64b015763785 has a different version than expected. Expected: 118 - Actual: 124.
at new t (64285f5.modern.js:2)
at Object.next (64285f5.modern.js:2)
at A (64285f5.modern.js:2)
at C (64285f5.modern.js:2)
at e.value (64285f5.modern.js:2)
at 64285f5.modern.js:2
at Set.forEach (<anonymous>)
at Object.next (64285f5.modern.js:2)
at A (64285f5.modern.js:2)
at C (64285f5.modern.js:2)

## Version of Vue Storefront

- [ ] Vue Storefront
- [X] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: 

## Additional information

The client wants to go live in the middle of this week and this error is blocking the release.

**Comment by andrzejewsky** [comment] 2020-11-30 17:12
probably fixed by https://github.com/DivanteLtd/vue-storefront/pull/5264 even though, I think there is something missing in the synchronization between cart and the checkout, seems like, after login out, checkout still keeps the old cart

**Comment by filipsobol** [comment] 2020-12-02 10:50
Issue is caused by project specific code and doesn't affect core.

**Closed by filipsobol** 2020-12-02 10:50 UTC
Labels: Next, bug, commercetools
