### ISSUE TITLE
Breadcrumbs tree structure on Product detail page is different

### ISSUE THREAD

**Issue by kovinka** [DivanteLtd/vue-storefront#1572] opened 2018-08-10 13:10 UTC
Breadcrumbs tree structure on Product detail page differs when page is opened from category and on page reload.

Steps to reproduce:

1. Open demo category page https://demo.vuestorefront.io/c/women-20
2. Click on "Minerva LumaTech™ V-Tee" product
3. Product details page for ""Minerva LumaTech™ V-Tee"" is opened
4. Breadcrumbs tree structure is: 
`Default Category / Women / Minerva LumaTech™ V-Te`
![screen shot 2018-08-10 at 16 02 29](https://user-images.githubusercontent.com/10535709/43959426-7b0c7f1a-9cb7-11e8-975b-3615cb4265b9.png)
5. Reload the page, breadcrumbs tree has another structure:
`Tees / Minerva LumaTech™ V-Tee`
![screen shot 2018-08-10 at 16 02 50](https://user-images.githubusercontent.com/10535709/43959432-7f5e5e08-9cb7-11e8-997f-ea20cfe6a808.png)

**Comment by pkarw** [comment] 2018-08-10 13:11
This is because when You enter product URL directly we don't have the category context and product can be assigned to more than one category. VS is currently creating the breadcrumb probably from the first cateogry assigned to the product (to be checked) - which is not always the "root" one

**Comment by filrak** [comment] 2018-08-15 19:54
@pkarw shouldn't we fix it?

**Closed** 2018-09-27 12:38 UTC

**Comment by themreza** [comment] 2020-01-21 22:26
This bug still exists: https://i.imgur.com/XMkfIh3.gif
I can confirm it with our OpenCart connection as well, on Vue Storefront v1.11.0

**Comment by pkarw** [comment] 2020-01-22 08:31
@themreza the breadcrumbs is the same as in containing category ("All / Gear") with just product title attached; it was like this from 0.3MVP ;)

**Comment by themreza** [comment] 2020-01-23 18:19
@pkarw 
I checked the two online demos demo.storefrontcloud.io on v1.10.5 and next.storefrontcloud.io on v1.11.0 and this the bug only happens on v1.11.0.

The behavior is strange and in my opinion not normal (even if navigated from different parent categories) that a product should have a different breadcrumb when reloading the same URL.

Please look at this side-by-side demo and the moment I refresh the page.

https://i.imgur.com/WWDHdG7.mp4
