### ISSUE TITLE
Product image does not show on reload (mobile browser)

### ISSUE THREAD

**Issue by envodev** [DivanteLtd/vue-storefront#2834] opened 2019-04-29 14:01 UTC
When viewing the demo app on a mobile browser (I tried Chrome, on Android 7), open up any product page, all good, now reload the page (pull-to-refresh), the product image does not load (just shows the placeholder), and the product description remains partially hidden unresponsive to touch.

**Comment by pkarw** [comment] 2019-04-29 14:03
I have this on mobile - but only on demo; not on next ...
@envodev can You please check https://next.storefrontcloud.io ?

**Comment by envodev** [comment] 2019-04-29 14:10
Confirmed no such issue on https://next.storefrontcloud.io, what is the difference between demo and next?

**Comment by omercan** [comment] 2019-04-29 15:40
Still same on my Android Phone, Google Chrome Version 74.0.3729.112

**Comment by pkarw** [comment] 2019-04-29 15:52
Guys in my case (iOS / chrome) it’s some JS issue or DOM Exception - blocking the js to work at all after full page reload on product and category pge

**Comment by pkarw** [comment] 2019-04-29 16:00
Related to https://github.com/DivanteLtd/vue-storefront/issues/2641 - it should work just fine on next (1.90)

**Comment by pkarw** [comment] 2019-04-29 16:03
On the screen posted by @omercan ir seems like this issue is different than the original one posted by @envodev (this one is fixed in 1.9). Looks like some problem with css rule setting the placeholder / image as background - fix proposed by @patzick skme long time ago

**Comment by pkarw** [comment] 2019-04-29 16:05
> Confirmed no such issue on https://next.storefrontcloud.io, what is the difference between demo and next?

This issue Jaś ben fixed with fix for #2641 however i haven’t tested the fix on Android - this May causes the problem @omercan posted

**Comment by ArturDivante** [comment] 2019-04-30 11:39
@omercan - We tried to reproduce this issue, on real devices and browserstack, with no effect - with current Chrome version. Behavior u presented on screenshot occurs only for a brief moment, when you reload page after clearing cache - but pictures always load correctly after brief delay. Are you sure, it wasn't related to some connection delay?

**Comment by omercan** [comment] 2019-04-30 13:25
@ArturDivante - Still same with both on incognito and normal browsing mode. Also experiencing the same bug on another device: OnePlus 6T. When I touch the product on the category page or main page, I can see the images on the category page for a while(Like 0.1 seconds.) before the redirection to the detail page.

**Comment by filrak** [comment] 2019-04-30 16:01
@omercan please dismiss add to homescreen box and see if you have another one below. Chrome can not load images when connection is słow

**Comment by pkarw** [comment] 2019-04-30 16:18
Closing while waiting for more materials from @omercan as we can’t reproduce this issue otherwise

**Comment by omercan** [comment] 2019-04-30 16:28
https://youtu.be/HBaQGKqzDNI

See attached video please.

**Comment by omercan** [comment] 2019-04-30 16:35
Remote debug: no console activity.

https://youtu.be/i0ZbczqKC6g

**Comment by pkarw** [comment] 2019-04-30 17:49
@omercan thanks! Could you please include a network tab view to check if the images are being downloaded at all?

**Comment by omercan** [comment] 2019-04-30 18:05
Here it is: https://www.dropbox.com/s/m1x77o4t0tixx6x/Screenshot%202019-04-30%2021.05.26.png?dl=0

**Comment by pkarw** [comment] 2019-04-30 18:28
Sorry for bothering You but I belive we need a screen of nertowrk tab for exactly the screen where you’re facing issues - products in category without the images I belive :)

**Comment by pkarw** [comment] 2019-04-30 18:28
@filrak @patzick maybe some change in newest chrome is causing this issue with lazy loading?

**Comment by omercan** [comment] 2019-04-30 19:19
@pkarw I navigated on both home screen and categories. The network tab is this after navigating between them.

**Comment by pkarw** [comment] 2019-04-30 19:36
@omercan ok so I see. Please do check if you have Chrome native lazy loading enabled and if so / please disable it and help if that helps: https://www.ghacks.net/2019/04/24/chrome-74-stable-is-out-with-dark-mode-and-lazy-loading-support/

**Comment by omercan** [comment] 2019-04-30 19:43
@pkarw It was default, I switched to Enabled but still same.

**Comment by pkarw** [comment] 2019-05-01 16:05
@omercan thanks! It's very hard for us to reproduce this issue, do You have any way to try to debug this issue by playing with some CSS / lazy-load settings of `ProductTile.vue` component?

**Comment by omercan** [comment] 2019-05-01 19:03
@pkarw I can.

**Comment by omercan** [comment] 2019-05-03 09:37
@pkarw Waiting for your recommendations.

**Comment by pkarw** [comment] 2019-05-03 09:47
@omercan its hard for me to recommend anything specific to be honest - by some reason lazy loading is not working properly. You might want to start with disabling Vue-lazyload on ProductTile and setting just the plain <img tags instead - please let me know if it solves this issue for You?

**Comment by filrak** [comment] 2019-05-05 19:47
@omercan also please try those (assuming this problem occurs on your local installation too):
- in `core/app.ts` find `Vue.use(VueLazyload, {attempt: 2, preLoad: 1.5})`, change it to `    Vue.use(VueLazyload, {attempt: 2, preLoad: 1.5, observer: true})` and check if problem still exists.. It's another way to detect if element entered viewport with intersection observer API.  This will tell us if the problem is in DOM elements size misscalcualtions.
- If above test will fail add some console logs on `ProductTile` that are fired when component enters viewport. You can use intersection observer API to make it easier. This will tell us if the fault is on the library.

**Comment by pkarw** [comment] 2019-05-09 05:35
Hi @omercan, I just wanted to kindly ask if there were any updates regarding this issue? :)

**Comment by pkarw** [comment] 2019-05-12 08:06
Closing the issue as it's not possible to reproduce this issue in the control env.

**Closed** 2019-05-12 08:06 UTC
Labels: P1: Urgent, bug
