### ISSUE TITLE
Instant checkout button is not visible in the cart sidebar

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#3569] opened 2019-09-17 12:53 UTC
## Current behavior

Instant checkout button is not visible in the cart sidebar, so I cannot use this option to place an order.
![Selection_071](https://user-images.githubusercontent.com/49188852/65043075-8305f300-d95a-11e9-95d1-f7ecf2c94a0c.png)

## Expected behavior

There is a visible Instant checkout button in the cart sidebar, so I can place an order using this option.

## Steps to reproduce the issue

1. Go to https://test.storefrontcloud.io/
2. Add any product to the cart
3. Open a cart sidebar clicking on the cart icon

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 76
- OS: ubuntu 18.04 LTS

## Additional information

There is no difference if I'm logged in or not.

**Comment by andrzejewsky** [comment] 2019-09-19 19:02
@GabiDivante are you sure? For me everything is ok (newest develop): 
<img width="1233" alt="Screenshot 2019-09-19 at 20 59 10" src="https://user-images.githubusercontent.com/7943292/65272979-703d1b00-db20-11e9-99d9-bdfd8eafea2a.png">

Please text me on slack, maybe I'm trying to reproduce it on the wrong way.

**Comment by alinadivante** [comment] 2019-09-20 07:35
@andrzejewsky The problem exists only in the test environment https://test.storefrontcloud.io/ (in the latest develop is ok).
This shouldn't be due to the Magento configuration, because it is the same Magento test.

**Comment by pkarw** [comment] 2019-09-20 07:37
Seemingly the test.storefrontcloud.io has this module disabled; @patzick can you please confirm?

**Comment by pkarw** [comment] 2019-09-20 07:37
I'm closing the issue bc. the Instant Checkout works on develop for me too

**Closed by pkarw** 2019-09-20 07:37 UTC
Labels: P3: Normal, QA rejected, bug
