### ISSUE TITLE
Store Wishlist to server

### ISSUE THREAD

**Issue by adityasharma7** [DivanteLtd/vue-storefront#3803] opened 2019-11-12 07:36 UTC
## What is the motivation for adding / enhancing this feature?

Currently, the wishlist is stored at only client's end only.  Implement logic such that if backend sync is enabled, it can be stored to the backend. 
Storing a wishlist on the server may add a lot of value specifically when recommending products and customer specific promotions.

## What are the acceptance criteria 

- [ ] Provision configuation file
- [ ] AddToWishlist component should honor config.
- [ ] Logic to make API calls to server

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment] 2019-11-12 11:18
This is a duplicate of #709

**Closed by pkarw** 2019-11-12 11:18 UTC
Labels: P4: Nice to have, feature request

**Comment by adityasharma7** [comment] 2019-11-12 13:16
Thanks @pkarw for pointing that. I will try to check for an existing issue before making further issues.
