### ISSUE TITLE
Size changing is not working in cart "edit mode"

### ISSUE THREAD

**Issue by dmytrokravch** [DivanteLtd/vue-storefront#4104] opened 2020-02-19 09:36 UTC
## Current behavior

When I try to change size in "edit mode" it does not change

## Expected behavior

He must change

## Steps to reproduce the issue

1 Add this product to shopping cart:
https://test.storefrontcloud.io/men/tops-men/tanks-men/tanks-17/vulcan-weightlifting-tank-693.html?childSku=MT06-XS-Black
2 try to change size

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
Browser: Google Chrome Version 81.0.4044.17
OS: Win 10
Node: 10.15.2
Code Version: 1.11.1

## Additional information
In version 1.11.0 there was no such problem

**Comment by pkarw** [comment] 2020-02-20 19:40
@andrzejewsky we exchanged on Slack on this issue some time ago (2 weeks?) - I forgot what was the cause in here; it was something like totals not being updated after editing the item(?)

**Comment by Michal-Dziedzinski** [comment] 2020-02-21 07:59
@pkarw exactly, totals don't update, I'm looking for the source of the problem

**Comment by Michal-Dziedzinski** [comment] 2020-02-26 11:14
it's working on hotfix/v1.11.2 branch

**Comment by pkarw** [comment] 2020-02-26 18:52
@gibkigonzo can we close this tomorrow?

**Comment by Michal-Dziedzinski** [comment] 2020-02-27 08:54
@pkarw at 1.11.2 produc at microcart has no `totals` property so data are going from `product.options` not from `product.totals.options`. I mean you wrote at https://github.com/DivanteLtd/vsf-capybara/issues/223 that 

> product options infromations came from Totals 

which is not always true

**Comment by pkarw** [comment] 2020-02-27 08:55
yes, it has no totals when `api/totals` is not executed properly - I guess that's the reason; @gibkigonzo is workin on this I guess

**Closed** 2020-02-27 14:16 UTC
Labels: P2: Important, bug
