### ISSUE TITLE
When cart contain only "Overnight duffle" product, provided by customer discount code was not applied

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2872] opened 2019-05-08 11:09 UTC
## Steps to reproduce the issue
1. Go to Gear category → Bags
2. Open **Overnight Duffle** product and press Add to cart
3. Open Shopping cart
4. Add  " **mmtest** " discount code
5. Add another product to cart and again add " **mmtest** " discount code
6. Remove both product from the cart
7. Again add to cart **Overnight Duffle** product 
8. On the cart u will see " **mmtest** " discount code so try to remove it and add new discount code (for example " **armani** ") 

## Current behavior
Problem with discount code for **Overnight Duffle**  product.
Provided by customer discount code was not applied for this product.

After adding another product to the cart and providing again the same discount code, code was applied and discount recalculate properly.
What's more: if user removed products from the cart and again he will add **Overnight Duffle**  product then he will see  **mmtest** " discount code applied, but he couldn't remove it or change for other discount code.

(Providing different code than on a first step doesn't change anything - situation is the same)

![doscount_code](https://user-images.githubusercontent.com/47415585/57371371-de48fd00-7192-11e9-8c18-bf304c1a985e.gif)

## Expected behavior
Provided by customer discount code should be applied for  *Overnight Duffle** product.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: 

## Additional information
https://demo.storefrontcloud.io/

**Comment by pkarw** [comment] 2019-05-10 11:58
The discount code is being taken from the platform totals: https://github.com/DivanteLtd/vue-storefront/blob/e7f8b0f3853591130c8083eb3be53d53a15b6dc9/core/modules/cart/store/getters.ts#L58

I believe the problem is that the totals were not correctly refreshed after clearing the items / adding new products. It requires some debugging to check why the discount code is still there but not applied

**Comment by pkarw** [comment] 2019-05-12 07:33
Maybe - just a maybe it's related to https://github.com/DivanteLtd/vue-storefront-api/issues/228 and https://github.com/DivanteLtd/vue-storefront-api/pull/231.

We're currently calling just the `shipping-information` for totals. Probably we need to change it to `collect-totals` instead to make surre totals are always updated

**Comment by pkarw** [comment] 2019-05-14 06:40
Can't reproduce it on `develop` :/

**Comment by alinadivante** [comment] 2019-05-14 07:09
@pkarw Please, try again now. I changed shipping methods in Magento (only Free shipping is enabled) and I' able to reproduce it now

**Comment by pkarw** [comment] 2019-06-03 09:01
It was related to shipping methods and it's been probably fixed by #2887 could You please check it?

**Comment by alinadivante** [comment] 2019-06-03 09:21
yeah, works fine! :)

**Closed** 2019-06-03 09:23 UTC
Labels: 3: Medium, P3: Normal, QA approved on branch, bug
