### ISSUE TITLE
The hover effect on the buttons in the header is moved one pixel down.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2893] opened 2019-05-14 06:14 UTC
## Current behavior
By hovering over the buttons in the header, hover effect moves one pixel down.
![image](https://user-images.githubusercontent.com/36628922/57674767-66f6eb80-7620-11e9-817d-45c96b39935e.png)

## Expected behavior
Hovering effect should be aligned with the header.

## Steps to reproduce the issue
1. Hover over any buttons in the header
2. Look at hamburger menu

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by Hackbard** [comment] 2019-05-24 08:13
Can't reproduce this Bug on Mac with Chrome 74, Safari 12.1 and Firefox 60.3

**Comment by dlandmann** [comment] 2019-05-24 11:08
Error only on **Startpage** visible, if browsercache (Chrome and Safari testet) cleaned.

**Comment by RGijsberts** [comment] 2019-05-24 13:27
The Account button in the header, the one with the avatar, contains an element: <i class="material-icons block" data-v="">account_circle</i> 

As you can see this element has two classes; .material-icons and .block .
.material-icons assigns a display:inline-block rule to this element, while .block should override this by assigning a display: block rule.

It seems that is a matter of which stylesheet is loaded first because on https://next.storefrontcloud.io/ I can reproduce this error by refreshing multiple times. Sometimes the bug appears and sometimes it doesn't.

The styling rules for .material-icons are located in a css file of which the load is initiated by webfont.js, the function is located in index.template.html

**Comment by pkarw** [comment] 2019-07-14 07:17
Przemek can you take this one as well?

**Comment by patzick** [comment] 2019-07-26 10:33
Fixed with 1.10

**Closed by patzick** 2019-07-26 10:33 UTC
Labels: 1: Easy, bug, vs-hackathon
