### ISSUE TITLE
VS doesn't handle negative product stocks

### ISSUE THREAD

**Issue by Tjitse-E** [DivanteLtd/vue-storefront#1055] opened 2018-04-19 09:20 UTC
Problem: sometimes in Magento, a product has a negative stock. For example:
![stocks](https://user-images.githubusercontent.com/14849044/38982970-8897cdf8-43c3-11e8-8509-c190fdb809be.png)

This is causing VS to crash for that particular product:
![negative-stock-crash](https://user-images.githubusercontent.com/14849044/38983009-a22ff164-43c3-11e8-8bea-1e53f61a2e28.png)

I'm using the latest master of both the frontend and the API.

**Comment by Tjitse-E** [comment] 2018-04-19 12:04
@pkarw you're right, it's not the negative qty, but i've not yet discovered what's wrong with these products. The special price is also missing.

**Comment by pkarw** [comment] 2018-04-27 08:37
@Tjitse-E any updates on that? Do you need some help?

**Comment by pkarw** [comment] 2018-05-10 09:28
I've close this one and need your es dump to try to figure out what's wrong. The issue is not with the negative stock anyway

**Closed** 2018-05-10 09:27 UTC
