### ISSUE TITLE
RWD - Add fixed width for sidebar with filters on products listing

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#279] opened 2017-11-08 08:32 UTC
![23](https://user-images.githubusercontent.com/18116406/32538833-b41eb328-c467-11e7-975f-c407127ffd4a.png)

**Comment by pkarw** [comment] 2017-11-09 17:10
@karolbzik cannot reproduce this one seems to be fixed

**Comment by patrykpiston** [comment] 2017-11-20 13:20
Yeah It's been fixed in the pre-demo MR. Sorry for leaving it in.

**Closed by patrykpiston** 2017-11-20 13:20 UTC
Labels: bug
