### ISSUE TITLE
Refactor core/store/index.js - move the localForage references to modules

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2081] opened 2018-12-12 11:28 UTC
## What is the motivation for adding / enhancing this feature?

This method should be decentralized to modules:
https://github.com/DivanteLtd/vue-storefront/blob/095e5301b8d50c0c9d77694189e00f0f64aa5682/core/store/index.ts#L139

**Comment by filrak** [comment] 2019-01-12 15:38
I made a duplicate of this issue. Tomek Kikowski is working on It

**Closed by filrak** 2019-01-12 15:38 UTC
Labels: refactor, vs-hackathon
