### ISSUE TITLE
Broken first load on homepage and CMS pages in production

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#3485] opened 2019-09-05 08:41 UTC
## Current behavior
Everything works correct in development mode, but in production no images is showing up and menu is broken on the Homepage and CMS pages. 

(If Im loading a category page and navigate to Homepage everything works correct. )
![image](https://user-images.githubusercontent.com/5425824/64325933-53093800-cfc9-11e9-976f-a4490777b6d3.png)

## Expected behavior
Should work as in development mode

## Repository
v1.10.1

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: 
- Node: v10.16.3
- Code Version: v1.10.1

## Additional information
Ping @jorkvist at slack if you want link to production to check it.

**Comment by pkarw** [comment] 2019-09-05 09:45
I can confirm this issue; we're workin on solution right now; thanks

**Comment by cewald** [comment] 2019-09-06 08:20
I think the bug comes in between this two commits in `develop` branch:
9dfc06c742055f831557ff442d011d300430f034 - a68315c33681cc57842e64a670cbcd8b2df71d84

I would recommend a `git bisect` to find the faulting commit.

**Comment by pkarw** [comment] 2019-09-06 08:32
@cewald and @jorkvist please test our solution to this issue: https://github.com/DivanteLtd/vue-storefront/pull/3499

**Comment by cewald** [comment] 2019-09-06 08:46
@pkarw Thanks, I'm at the hackathon and will test it quickly.

**Comment by cewald** [comment] 2019-09-06 09:07
@pkarw 
The PR above works but is only in master.
Is this a fix that will be in develop too?

**Comment by pkarw** [comment] 2019-09-06 09:38
Thanks for checking! Yeah @patzick will merge it in

**Comment by alinadivante** [comment] 2019-09-30 11:41
@patzick please check if the master has been merged into development, because I can reproduce it on release 1.11
![image](https://user-images.githubusercontent.com/36628922/65875664-0296b780-e388-11e9-8df6-12245b0c5125.png)

**Comment by pkarw** [comment] 2019-09-30 16:22
@andrzejewsky please do recheck

**Comment by andrzejewsky** [comment] 2019-10-02 17:08
ok for me works, @alinadivante / @ArturDivante Can you confirm with the newest develop?

**Comment by alinadivante** [comment] 2019-10-03 05:31
@andrzejewsky for a short while I have this problem. After 1-2 seconds all the elements are displayed.

**Comment by andrzejewsky** [comment] 2019-10-08 16:15
@jorkvist Is it still occurs for you? Could you check latest release? It seems like on the weaker connections there is a kind of blink - you don't see all of images but they are displayed after few seconds when they just loaded.

**Closed** 2019-10-17 07:41 UTC
Labels: P1: Urgent, bug
