### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS in production mode on latest develop branch

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3302] opened 2019-07-27 21:05 UTC
## Current behavior

If I start the VSF like `yarn && yarn build && yarn start` in production mode after I update to the latest `develop` (cf566a0e672dda5a725a3f7688e5f9119123864b) branch, the process starts correctly but the VSF isn't available in browser and returns a `ERR_TOO_MANY_REDIRECTS` error.

If I look the logs via `yarn pm2 logs` I get the following error messages:
```bash
2019-07-27 22:51:43: Error during render : /
2019-07-27 22:51:43: TypeError: Object(...) is not a function
    at Object.<anonymous> (core/store/index.ts:49:25)
    at n (webpack/bootstrap:36:0)
    at Object.<anonymous> (core/lib/storage-manager.ts:58:71)
    at n (webpack/bootstrap:36:0)
    at Object.<anonymous> (core/modules/url/helpers/index.ts:15:2)
    at n (webpack/bootstrap:36:0)
    at Object.<anonymous> (core/helpers/validators.ts:2:56)
    at n (webpack/bootstrap:36:0)
    at Object.<anonymous> (core/app.ts:1:0)
    at Object.<anonymous> (node_modules/core-js/modules/_redefine.js:4:10)
2019-07-27 22:51:43: Error during render : /error
2019-07-27 22:51:43: TypeError: Object(...) is not a function
    at Object.<anonymous> (core/store/index.ts:49:25)
    at n (webpack/bootstrap:36:0)
    at Object.<anonymous> (core/lib/storage-manager.ts:58:71)
    at n (webpack/bootstrap:36:0)
    at Object.<anonymous> (core/modules/url/helpers/index.ts:15:2)
    at n (webpack/bootstrap:36:0)
    at Object.<anonymous> (core/helpers/validators.ts:2:56)
    at n (webpack/bootstrap:36:0)
    at Object.<anonymous> (core/app.ts:1:0)
    at Object.<anonymous> (node_modules/core-js/modules/_redefine.js:4:10)
```

or:
```bash
Error during render : /error
TypeError: Object(...) is not a function
    at Object.<anonymous> (core/store/index.ts:9:5)
    at n (webpack/bootstrap:25:0)
    at Object.<anonymous> (core/lib/storage-manager.ts:58:71)
    at n (webpack/bootstrap:25:0)
    at Object.<anonymous> (node_modules/lodash-es/omit.js:57:15)
    at n (webpack/bootstrap:25:0)
    at Object.<anonymous> (core/lib/logger.ts:171:26)
    at n (webpack/bootstrap:25:0)
    at Object.<anonymous> (core/app.ts:1:0)
    at Object.<anonymous> (core/app.ts:125:29)
```

The site works without problems in develop mode via `yarn dev`.

I don't have a glue yet what causes the exception and going to try reproduce it on another machine. Does anybody else have this behavior or just me? If so I'm sorry for the opened issue.

**UPDATE:** I could now reproduce it on a plain Ubuntu machine using Node `v10.16.0`. FYI I'm using the `https://test.storefrontcloud.io` API endpoint for testing. But it appears in my custom API as well.

## Expected behavior

See the storefront

## Steps to reproduce the issue

Checkout `develop` branch on commit cf566a0e672dda5a725a3f7688e5f9119123864b and try to start it in production mode, something like:

```bash
yarn
yarn build
yarn start
```

## Repository

cf566a0e672dda5a725a3f7688e5f9119123864b

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome/FF
- OS: OSX
- Node: v10.15.3
- Code Version: cf566a0e672dda5a725a3f7688e5f9119123864b

**Comment by cewald** [comment] 2019-07-28 09:52
After some research I found out that it stopped working with the following commit b6eea29ce1410f8100efa391680493722b917e18 of PR #3255.

**Comment by dlandmann** [comment] 2019-07-29 08:51
I can confirm this behavior with the latest develop-branch.

**Comment by pkarw** [comment] 2019-07-30 06:25
@filrak what can we do about this issue?

**Comment by pkarw** [comment] 2019-08-05 06:21
@lukeromanowicz what's the status in here/

**Comment by lukeromanowicz** [comment] 2019-08-05 19:03
@pkarw I've found the root cause. I will push a fix tomorrow.

**Comment by cewald** [comment] 2019-08-07 06:14
It's is working again.
Thanks! :)

**Comment by cewald** [comment] 2019-08-07 06:15
Am I allowed to close the issue or will it crash your workflow?

**Comment by pkarw** [comment] 2019-08-09 10:46
@cewald thanks for the confirmation, closing :)

**Closed** 2019-08-09 10:46 UTC
Labels: 3: Medium complexity, P2: Important, bug
