### ISSUE TITLE
Page reload on checkout causes errors

### ISSUE THREAD

**Issue by kovinka** [DivanteLtd/vue-storefront#1642] opened 2018-08-28 08:48 UTC
When manually reload the Checkout page, it redirects to Homepage, Checkout component isn't updated (still displayed in storefront), getting js errors (please check screenshot), checked on https://demo.vuestorefront.io/.
<img width="1433" alt="screen shot 2018-08-28 at 11 27 23" src="https://user-images.githubusercontent.com/10535709/44711843-fa4eb780-aab7-11e8-822d-e799c608f1f5.png">

**Comment by pkarw** [comment] 2018-08-29 11:30
Thanks, it has been fixed in the develop branch and You can check it on https://test.vuestorefront.io

**Closed by pkarw** 2018-08-29 11:30 UTC

**Comment by kovinka** [comment] 2018-08-29 15:28
@pkarw checked on test env, page is not redirected now, but still have js errors and buttons/links are not clickable:
<img width="1272" alt="screen shot 2018-08-29 at 18 24 20" src="https://user-images.githubusercontent.com/10535709/44798081-50575400-abb9-11e8-8499-2db7f9b16598.png">

**Comment by pkarw** [comment] 2018-08-29 18:30
I can't reproduce this error (Chrome 68, MacOSX); what's your system? Do you have the same issue on Your local instance with the latest develop branch checked out?

**Comment by kovinka** [comment] 2018-08-29 18:39
i'm also using Chrome 68, MacOS. 
For testing i directly opened checkout https://test.vuestorefront.io/checkout link.
In Firefox it's also reproduced:
<img width="1571" alt="screen shot 2018-08-29 at 21 37 43" src="https://user-images.githubusercontent.com/10535709/44808033-d7192a80-abd3-11e8-91a5-5de0c1864604.png">
Will check locally and update comment later with result.

**Comment by PatrickKluwig** [comment] 2019-06-18 13:28
Hey, I also got some errors reloading the checkout page. Error Log below:
![image](https://user-images.githubusercontent.com/37376833/59688315-b7dc9f80-91dd-11e9-98eb-99230930f932.png)

**Comment by sebastianrothbucher** [comment] 2019-11-23 18:43
Even though the concrete issue is fixed: this kind of issues keeps popping up. 

It's hard to discover such errors as Vue in production mode does no longer run ```assertNodeMatch``` (which would otherwise detect and kick off a repair). Aside from running ```yarn dev``` (which has Vue production mode turned *off* and print out the node where the error occurs on console). 

It's generally a bad idea to render content (```v-if``` et al) based on ```isServer```.  ```v-show``` would work - but may not be sufficient. 

If you really must (and sometimes, you do), the only way out is to have an ```myIsServer: true``` defined in data and then use ```mounted``` to issue ```this.$nextTick(() => this.myIsServer = false)```. The point is to *not change any pre-rendered contents at all until hydration is finished* (hence ```$nextTick```). This will avoid such errors and stuck UIs although I would not bet all of VSF's own code is free of content rendered based on ```isServer```. Unfortunately, Vue in production mode lets differences pass and then fail (seeminly) arbitrarily. 

Thought it might be helpful to share this - as I did some debugging in this space as well. BTW: for client-only-rendering, there is a great ```vue-no-ssr``` package (which VSF also uses at some spots). For server-only, it's pretty straightforward to write analogous code to this. 

Again: hope it helps to share that ```v-if="isServer"``` is potentially dangerous and the solution might lie in avoiding this.
