### ISSUE TITLE
Add chosen filters to url

### ISSUE THREAD

**Issue by kacperknapik** [DivanteLtd/vue-storefront#385] opened 2017-12-07 14:22 UTC
We should be able to visit specific category page from a link with filters selected.
At the moment what we have is an url, which directs us to a category page and it's default setup.

What we need to do is to append chosen filters to the url, so when the client visits a link, eg. `/c/foo/Red/XS/50-100`, he gets `foo` category, with `Red`, `XS` and `$50-$100` filters selected.

**Comment by pkarw** [comment] 2017-12-29 15:38
@akbarik not sure if it’s clear from the description but this issue is about Category page (Product page already allows users to pass the variants as link parameter)

Please take care of SSR mode.

**Comment by akbarik** [comment] 2017-12-29 15:53
Yes, it is clear. Thank you.

**Comment by mercs600** [comment] 2018-06-02 13:00
I'm closing this issue because this is duplicate of #1104

**Closed by mercs600** 2018-06-02 13:00 UTC
Labels: good first issue
