### ISSUE TITLE
Reviews are not displayed on PDP's

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2660] opened 2019-03-27 09:30 UTC
## Related issue
#2594

## Current behavior
Reviews are correctly added, displayed in Magento, but even approved ones are not displayed in VSF

## Expected behavior
Accepted reviews are displayed on product pages 

## Steps to reproduce the issue
1. Open any product page in VSF
2. Submit a review (filling all required fields)
3. Login to magento and approve the review. 
4. Open same product page again in VSF

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
All (demo, next, test)

## Environment details
- Browser: All
- OS: All

## Additional information
Problem applies to freshly added reviews as well as the ones that are in magento for some time. magento currently stores over 400 reviews on diffrent status, including many "approved' ones. As far as i could check, **none** of them is currently displayed in VSF, on any test environment.

**Comment by pkarw** [comment] 2019-03-30 08:20
Related to: #2668

**Comment by pkarw** [comment] 2019-03-30 08:25
@afirlejczyk can You please check if it's related to #2668 and if it solves this issue?

**Comment by afirlejczyk** [comment] 2019-04-04 18:58
@ArturDivante.

Please check if this problem occurs on Simple Product (for the configurable product we have a bug #2668).
 
After aproving the review in Magento, you have to re-import reviews (with mage2vsf) . 
Approved reviews won't show automatically on the vsf.

**Comment by alinadivante** [comment] 2019-06-12 10:53
@pkarw could you look on it? because I added new reviews, I accepted them in magento and @patzick did re-index + re-import reviews with mage2vsf and it didn't help..

**Comment by pkarw** [comment] 2019-06-12 11:29
I can't take a look at it by myself but maybe somebody else can? @afirlejczyk was the one who made reviews happen so her advice here is priceless

**Comment by afirlejczyk** [comment] 2019-06-13 07:28
It looks like changes made in

https://github.com/afirlejczyk/vue-storefront/commit/5fce4fa53e0ff5d9271b4d9bf56bc025f53a1a99
are not available on demo (are not available in master branch) -> VSF still is trying to get reviews for simple products -> which is wrong.
By default Magento assign/display reviews only assing to configurable products.


@pkarw 
@patzick 

This can be test only after you will merged this fix into master
https://github.com/DivanteLtd/vue-storefront/pull/2668

**Comment by pkarw** [comment] 2019-06-13 07:35
@alinadivante have You tested it on develop?

**Comment by afirlejczyk** [comment] 2019-06-13 08:11
Please update magento2-review-api module
https://github.com/DivanteLtd/magento2-review-api/ on your Magento and re-import reviews. 

There were a bug and all exported reviews were assign to product with id 1.

**Comment by alinadivante** [comment] 2019-06-13 11:24
yes, on develop

**Comment by pkarw** [comment] 2019-06-13 17:08
the issue is with the demo instance where the review api module hasn't been yet updated. Agata is contacting our devops to update it properly

**Comment by afirlejczyk** [comment] 2019-06-14 10:20
@pkarw @alinadivante 
Module magento2-review-api is updated, please re-import reviews one more time.

**Comment by pkarw** [comment] 2019-06-19 07:33
I've tested it on localhost - and it works just fine: https://www.dropbox.com/s/kxxw6ix1reyr8y7/Screenshot%202019-06-19%2009.32.39.png?dl=0

**Closed by pkarw** 2019-06-19 07:33 UTC
Labels: QA rejected, bug
