### ISSUE TITLE
Some links from Footer direct on the same page (but with different URL)

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2344] opened 2019-02-02 13:48 UTC
## Current behavior
When user is for example on Store locator page and changes it on another from Footer, he is still on the same page, but with another URL.
## Expected behavior
Click on any links from Footer should direct on right page

## Steps to reproduce the issue
1. Go to Footer
2. Click on Store locator
3. Then click on any other link on the left side, for example Delivery

## Environment details
https://demo.storefrontcloud.io

**Comment by vue-kacper** [comment] 2019-02-02 19:13
It's not a bug - those are all static pages assigned to the same component

**Closed** 2019-02-02 19:38 UTC
Labels: bug, good first issue
