### ISSUE TITLE
Custom options on  Downloadable product not working properly

### ISSUE THREAD

**Issue by MarcoGrecoBitbull** [DivanteLtd/vue-storefront#2339] opened 2019-02-01 16:09 UTC
## Current behavior
if you try to add to cart a downloadable product with price zero that have custom options it fails and return error message about price but it happen because isn't possible select any available options
 
## Expected behavior
Options have to appears like magento2 enviroment:
http://demo-magento2.vuestorefront.io/luma-yoga-for-life.html

if you select nothing can't add to cart the product, otherwise add product with updated price 
 
## Steps to reproduce the issue
_ go to https://demo.vuestorefront.io/p/240-LV09/luma-yoga-for-life
_ not options appears
_ if you click add to cart error message occurs "Product price is unknown, product cannot be added to the cart!"

**Comment by pkarw** [comment] 2019-02-04 18:57
Related to: #2315

**Comment by pkarw** [comment] 2019-02-04 21:17
Closing this one as a duplicate of #2315; proper downloadable products support still need to be added

**Closed by pkarw** 2019-02-04 21:17 UTC
Labels: bug
