### ISSUE TITLE
"Filter by" has some problems

### ISSUE THREAD

**Issue by Able2Code** [DivanteLtd/vue-storefront#1793] opened 2018-09-29 11:00 UTC
Ex: https://demo.vuestorefront.io/c/gear-3
Try to filter by any criteria, then order and reorder more times.
Some times it returns all site items ordered and not only category specific items, in other cases it returns zero items.
Also how to reset left bar filter, or maybe remove only a specific filter from the search? When i choose any filter the url do not change, this is bad for SEO and for user who want share a specific collection.

**Comment by pkarw** [comment] 2018-09-29 11:58
Could you provide us please with some screenshots? I’ve tried to reproduce this issue on demo, gear category but without success

**Comment by pkarw** [comment] 2018-09-29 14:01
@vue-kacper can You check this one please?
@Able2Code thanks for reporting! Which browser are you using?

**Comment by Able2Code** [comment] 2018-09-29 14:04
@pkarw : Chrome 69 !

**Comment by pkarw** [comment] 2018-09-29 14:09
I think the problem is somewhere in here: 
https://github.com/DivanteLtd/vue-storefront/blob/514576f2dd4f77baa0e31202bda25d6717c5b5b9/core/pages/Category.js#L190

Probably we should avoid code duplication between onSortChanged and onGilterChanged (calling onFilterChanged when sort order changed - of course without any changes to filters (we need to support filterOption empty fort that case))

**Comment by pkarw** [comment] 2018-09-29 14:12
The second option is that sth changes the current category object (
https://github.com/DivanteLtd/vue-storefront/blob/514576f2dd4f77baa0e31202bda25d6717c5b5b9/core/pages/Category.js#L42)which is used for constructing the query

**Comment by pkarw** [comment] 2018-10-03 13:42
Closing it as I can't reproduce this issue  :-(

**Closed by pkarw** 2018-10-03 13:42 UTC
Labels: bug
